/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author yolos
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
        this.setLocationRelativeTo(null); //Centers form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        LoginMinimizeLabel = new javax.swing.JLabel();
        LoginExitLabel = new javax.swing.JLabel();
        LoginUsernameText = new javax.swing.JLabel();
        LoginPasswordText = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        LoginPasswordLabel = new javax.swing.JPasswordField();
        LoginUsernameLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 320));

        LoginLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        LoginLabel.setText("Login");

        LoginMinimizeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LoginMinimizeLabel.setText("-");
        LoginMinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMinimizeLabelMouseClicked(evt);
            }
        });

        LoginExitLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LoginExitLabel.setText("X");
        LoginExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginExitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginLabel)
                .addGap(204, 204, 204)
                .addComponent(LoginMinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginExitLabel)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginMinimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginExitLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(LoginLabel)
                .addGap(19, 19, 19))
        );

        LoginUsernameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginUsernameText.setText("Username");

        LoginPasswordText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginPasswordText.setText("Password");

        LoginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginPasswordLabel.setText("asdasdasd");
        LoginPasswordLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginPasswordLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginPasswordLabelFocusLost(evt);
            }
        });

        LoginUsernameLabel.setText("username");
        LoginUsernameLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginUsernameLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginUsernameLabelFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginPasswordText)
                    .addComponent(LoginUsernameText))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginPasswordLabel)
                    .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUsernameText)
                    .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPasswordText)
                    .addComponent(LoginPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginUsernameLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginUsernameLabelFocusGained
        
        //Sets the text to nothing and text color changed to black when focus on the label has been gained.
        if(LoginUsernameLabel.getText().trim().toLowerCase().equals("username"))
       {
           LoginUsernameLabel.setText("");
           LoginUsernameLabel.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_LoginUsernameLabelFocusGained

    private void LoginUsernameLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginUsernameLabelFocusLost
        //Sets Text to username if their is nothing entered or there has been username entered when focus on the Label has been lost.
        if(LoginUsernameLabel.getText().trim().toLowerCase().equals("") || 
              LoginUsernameLabel.getText().trim().toLowerCase().equals("username"))
       {
           LoginUsernameLabel.setText("username");
           LoginUsernameLabel.setForeground(new Color(153,153,153));
           
       }
    }//GEN-LAST:event_LoginUsernameLabelFocusLost

    private void LoginPasswordLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginPasswordLabelFocusGained
        String pass = String.valueOf(LoginPasswordLabel.getPassword());
        //Sets the text to nothing and text color changed to black when focus on the label has been gained.
        if(pass.trim().toLowerCase().equals("asdasdasd"))
       {
           LoginPasswordLabel.setText("");
           LoginPasswordLabel.setForeground(Color.BLACK);
       }
    }//GEN-LAST:event_LoginPasswordLabelFocusGained

    private void LoginPasswordLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginPasswordLabelFocusLost
        String pass = String.valueOf(LoginPasswordLabel.getPassword());
        //Sets Text to username if their is nothing entered or there has been username entered when focus on the Label has been lost.
        if(pass.trim().toLowerCase().equals(""))
       {
           LoginPasswordLabel.setText("asdasdasd");
           LoginPasswordLabel.setForeground(new Color(153,153,153));
           
       }
    }//GEN-LAST:event_LoginPasswordLabelFocusLost

    private void LoginExitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginExitLabelMouseClicked
        
        //Exit from the from when the exit button is pressed
        System.exit((0));
    }//GEN-LAST:event_LoginExitLabelMouseClicked

    private void LoginMinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMinimizeLabelMouseClicked
        
        //Minimize the form when the minimize label is pressed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_LoginMinimizeLabelMouseClicked

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        PreparedStatement st;
        ResultSet rs;
        
        String username = LoginUsernameLabel.getText();
        String password = String.valueOf(LoginPasswordLabel.getPassword());
        
        
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            st.setString(2, password);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                //new form shown
                Main_Menu form = new Main_Menu();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //current form close
                this.dispose();
                
            }else
            {
                // error message
                JOptionPane.showMessageDialog(null, "Invalid Username or Password","Login Error", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginExitLabel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel LoginMinimizeLabel;
    private javax.swing.JPasswordField LoginPasswordLabel;
    private javax.swing.JLabel LoginPasswordText;
    private javax.swing.JTextField LoginUsernameLabel;
    private javax.swing.JLabel LoginUsernameText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
